repo:
  - '*'

github-ations:
  - '.github/**/*.yml'

readme:
  - 'README.md'

packages-requirements:
  - 'requirements.txt'

packages-setup:
  - 'setup.py'

source:
  - 'src/**/*.py'

test:
  - 'test/*.py'

src:
  - 'src/*.py'

notebook:
  - 'notebook/*.ipynb'

datasets:
  - 'datasets/*'

weights:
  - 'weights/*'
